import { PermissionAction } from '@prisma/client';

export const PERMISSIONS = [
  ['companies.view', 'companies', PermissionAction.VIEW],
  ['companies.update', 'companies', PermissionAction.UPDATE],
  ['branches.view', 'branches', PermissionAction.VIEW],
  ['branches.create', 'branches', PermissionAction.CREATE],
  ['branches.update', 'branches', PermissionAction.UPDATE],
  ['branches.change_status', 'branches', PermissionAction.DISABLE],
  ['branches.set_main', 'branches', PermissionAction.UPDATE],
  ['branches.assign_users', 'branches', PermissionAction.UPDATE],
  ['users.view', 'users', PermissionAction.VIEW],
  ['users.create', 'users', PermissionAction.CREATE],
  ['users.update', 'users', PermissionAction.UPDATE],
  ['users.disable', 'users', PermissionAction.DISABLE],
  ['roles.view', 'roles', PermissionAction.VIEW],
  ['settings.view', 'settings', PermissionAction.VIEW],
  ['settings.update', 'settings', PermissionAction.UPDATE],
  ['categories.view', 'categories', PermissionAction.VIEW],
  ['categories.create', 'categories', PermissionAction.CREATE],
  ['categories.update', 'categories', PermissionAction.UPDATE],
  ['categories.disable', 'categories', PermissionAction.DISABLE],
  ['brands.view', 'brands', PermissionAction.VIEW],
  ['brands.create', 'brands', PermissionAction.CREATE],
  ['brands.update', 'brands', PermissionAction.UPDATE],
  ['brands.disable', 'brands', PermissionAction.DISABLE],
  ['units.view', 'units', PermissionAction.VIEW],
  ['units.create', 'units', PermissionAction.CREATE],
  ['units.update', 'units', PermissionAction.UPDATE],
  ['units.disable', 'units', PermissionAction.DISABLE],
  ['products.view', 'products', PermissionAction.VIEW],
  ['products.create', 'products', PermissionAction.CREATE],
  ['products.update', 'products', PermissionAction.UPDATE],
  ['products.disable', 'products', PermissionAction.DISABLE],
  ['products.import', 'products', PermissionAction.CREATE],
  [
    'product_compatibility.view',
    'product_compatibility',
    PermissionAction.VIEW,
  ],
  [
    'product_compatibility.manage',
    'product_compatibility',
    PermissionAction.UPDATE,
  ],
  ['services.view', 'services', PermissionAction.VIEW],
  ['services.create', 'services', PermissionAction.CREATE],
  ['services.update', 'services', PermissionAction.UPDATE],
  ['services.disable', 'services', PermissionAction.DISABLE],
  ['inventory.view', 'inventory', PermissionAction.VIEW],
  ['inventory.adjust', 'inventory', PermissionAction.UPDATE],
  ['inventory.transfer', 'inventory', PermissionAction.UPDATE],
  ['inventory.view_movements', 'inventory', PermissionAction.VIEW],
  ['inventory.view_low_stock', 'inventory', PermissionAction.VIEW],
  ['customers.view', 'customers', PermissionAction.VIEW],
  ['customers.create', 'customers', PermissionAction.CREATE],
  ['customers.update', 'customers', PermissionAction.UPDATE],
  ['customers.change_status', 'customers', PermissionAction.DISABLE],
  ['pos.access', 'pos', PermissionAction.VIEW],
  ['pos.validate_cart', 'pos', PermissionAction.UPDATE],
  ['sales.view', 'sales', PermissionAction.VIEW],
  ['sales.create', 'sales', PermissionAction.CREATE],
  ['sales.cancel', 'sales', PermissionAction.DISABLE],
  ['sales.view_detail', 'sales', PermissionAction.VIEW],
  ['cash.view', 'cash', PermissionAction.VIEW],
  ['cash.open', 'cash', PermissionAction.CREATE],
  ['cash.close', 'cash', PermissionAction.UPDATE],
  ['cash.manual_movement', 'cash', PermissionAction.CREATE],
  ['cash.view_sessions', 'cash', PermissionAction.VIEW],
  ['reports.view', 'reports', PermissionAction.VIEW],
  ['reports.sales', 'reports', PermissionAction.VIEW],
  ['reports.cash', 'reports', PermissionAction.VIEW],
  ['reports.inventory', 'reports', PermissionAction.VIEW],
  ['reports.customers', 'reports', PermissionAction.VIEW],
  ['reports.documents', 'reports', PermissionAction.VIEW],
  ['internal_documents.view', 'internal_documents', PermissionAction.VIEW],
  ['internal_documents.create', 'internal_documents', PermissionAction.CREATE],
  ['internal_documents.print', 'internal_documents', PermissionAction.VIEW],
  ['internal_documents.void', 'internal_documents', PermissionAction.DISABLE],
  ['fiscal.settings.view', 'fiscal', PermissionAction.VIEW],
  ['fiscal.settings.update', 'fiscal', PermissionAction.UPDATE],
  ['fiscal.providers.view', 'fiscal', PermissionAction.VIEW],
  ['fiscal.providers.configure', 'fiscal', PermissionAction.UPDATE],
  ['fiscal.documents.view', 'fiscal', PermissionAction.VIEW],
  ['fiscal.documents.create', 'fiscal', PermissionAction.CREATE],
  ['fiscal.documents.send', 'fiscal', PermissionAction.UPDATE],
  ['fiscal.documents.retry', 'fiscal', PermissionAction.UPDATE],
  ['fiscal.documents.view_events', 'fiscal', PermissionAction.VIEW],
  ['fiscal.documents.view_errors', 'fiscal', PermissionAction.VIEW],
] as const;
