-- Phase 2: billing grace period and automatic non-payment suspension.
ALTER TYPE "SubscriptionEventType" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_GRACE_STARTED';
ALTER TYPE "SubscriptionEventType" ADD VALUE IF NOT EXISTS 'COMPANY_AUTO_SUSPENDED_FOR_NON_PAYMENT';
ALTER TYPE "SubscriptionEventType" ADD VALUE IF NOT EXISTS 'COMPANY_REACTIVATED_AFTER_PAYMENT';
ALTER TYPE "SubscriptionEventType" ADD VALUE IF NOT EXISTS 'BILLING_OVERDUE_PROCESS_RUN';

ALTER TABLE "company_subscriptions"
  ADD COLUMN IF NOT EXISTS "suspendedAt" TIMESTAMP(3);
