export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  CASHIER = 'CASHIER',
  SELLER = 'SELLER',
  WAREHOUSE = 'WAREHOUSE',
  ACCOUNTING = 'ACCOUNTING',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
  INVITED = 'INVITED',
}

export enum BusinessType {
  SMALL_STORE = 'SMALL_STORE',
  BEAUTY_SALON = 'BEAUTY_SALON',
  BARBERSHOP = 'BARBERSHOP',
  MINIMARKET = 'MINIMARKET',
  GROCERY = 'GROCERY',
  TIRE_SHOP = 'TIRE_SHOP',
  AUTO_PARTS = 'AUTO_PARTS',
  HARDWARE_STORE = 'HARDWARE_STORE',
  CLOTHING_STORE = 'CLOTHING_STORE',
  PHONE_STORE = 'PHONE_STORE',
  COSMETICS_STORE = 'COSMETICS_STORE',
  SERVICE_BUSINESS = 'SERVICE_BUSINESS',
  OTHER = 'OTHER',
}

export enum CompanyStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum BranchStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum PermissionAction {
  VIEW = 'VIEW',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DISABLE = 'DISABLE',
}

export enum Currency {
  DOP = 'DOP',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  TRANSFER = 'TRANSFER',
  CREDIT = 'CREDIT',
}

export enum DocumentType {
  INTERNAL_RECEIPT = 'INTERNAL_RECEIPT',
  CONSUMER_INVOICE = 'CONSUMER_INVOICE',
  FISCAL_INVOICE = 'FISCAL_INVOICE',
}

export const DEFAULT_TAX_RATES = {
  EXEMPT: 0,
  REDUCED: 16,
  STANDARD: 18,
} as const;

export type DefaultTaxRate =
  (typeof DEFAULT_TAX_RATES)[keyof typeof DEFAULT_TAX_RATES];

export enum BusinessTemplate {
  SMALL_STORE = 'SMALL_STORE',
  BEAUTY_SALON = 'BEAUTY_SALON',
  BARBERSHOP = 'BARBERSHOP',
  MINIMARKET = 'MINIMARKET',
  GROCERY = 'GROCERY',
  TIRE_SHOP = 'TIRE_SHOP',
  AUTO_PARTS = 'AUTO_PARTS',
  HARDWARE_STORE = 'HARDWARE_STORE',
  CLOTHING_STORE = 'CLOTHING_STORE',
  PHONE_STORE = 'PHONE_STORE',
  COSMETICS_STORE = 'COSMETICS_STORE',
  SERVICE_BUSINESS = 'SERVICE_BUSINESS',
  OTHER = 'OTHER',
}

export enum CatalogStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum CategoryType {
  PRODUCT = 'PRODUCT',
  SERVICE = 'SERVICE',
  BOTH = 'BOTH',
}

export enum InventoryMovementType {
  MANUAL_ENTRY = 'MANUAL_ENTRY',
  ADJUSTMENT_IN = 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
  RETURN_IN = 'RETURN_IN',
  VOID_SALE_IN = 'VOID_SALE_IN',
  SALE_OUT = 'SALE_OUT',
  PURCHASE_IN = 'PURCHASE_IN',
}

export enum CustomerType {
  INDIVIDUAL = 'INDIVIDUAL',
  BUSINESS = 'BUSINESS',
}

export enum CustomerDocumentType {
  CEDULA = 'CEDULA',
  RNC = 'RNC',
  PASSPORT = 'PASSPORT',
  NONE = 'NONE',
}

export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum TaxpayerType {
  FINAL_CONSUMER = 'FINAL_CONSUMER',
  FISCAL_CONSUMER = 'FISCAL_CONSUMER',
  GOVERNMENT = 'GOVERNMENT',
  SPECIAL_REGIME = 'SPECIAL_REGIME',
  NONE = 'NONE',
}

export interface HealthResponse {
  status: 'ok';
  service: string;
  timestamp: string;
}
